/**
 * Created by kaihui on 2018/6/20.
 */
let vm=new Vue({
  el:"#app",
  created(){
    //如果localStorage有数据则拿数据，没有数据用自己的
    this.todos=JSON.parse(localStorage.getItem("todos"))||this.todos
    //监控hash值的变化，如果页面已经有hash了，重新刷新页面也要获取hash值
    this.hash=window.location.hash.slice(2)||this.hash
    window.addEventListener("hashchange",()=>{
      //当hash值变化，重新操作
      this.hash=window.location.hash.slice(2)
    },false)
  },
  directives:{
    focus(el,bindings){//el指代的是v-focus所在的标签,bindings指代v-focus的值
      if(bindings.value){
        el.focus()
      }
    }
  },
  data:{
    todos:[
      {
        id:1,
        info:"吃",
        isSelected:false
      },
      {
        id:2,
        info:"喝",
        isSelected:false
      },
      {
        id:3,
        info:"玩",
        isSelected:false
      },
    ],
    info:"",
    cur:"",
    hash:"all"
  },
  computed:{
    count(){
      return this.todos.filter(item=>!item.isSelected).length
    },
    filterTodos(){
      if(this.hash=="all"){
        return this.todos
      }
      if(this.hash=="finished"){
        return this.todos.filter(item=>item.isSelected)
      }
      if(this.hash=="unfinished"){
        return this.todos.filter(item=>!item.isSelected)
      }
      return this.todos
    }
  },
  methods:{
    add(){
      this.todos.push({
        id:this.count+1,
        info:this.info,
        isSelected:false
      })
      this.info=""
    },
    remove(todo){
      this.todos=this.todos.filter(item=>item!=todo)
    },
    /*allShow(){
      this.todoList=this.todos
    },
    finished(){
      this.todoList=this.todos.filter(item=>item.isSelected)
    },
    unfinished(){
      this.todoList=this.todos.filter(item=>!item.isSelected)
    },*/
    remember(todo){
      this.cur=todo
    },
    cancel(){
      this.cur=""
    }
  },
  watch:{
    todos:{
      handler(){
        localStorage.setItem("todos",JSON.stringify(this.todos))
      },deep:true
    }
  }
})


